Repository atoma-network/atoma-proxy, pull requests merged in 2025-03, with the labels that each got.

#277 build: update the `Cargo.lock`
  Cargo.lock
Labels: dependencies

#278 fix: add logs for loki
  Cargo.lock
  Cargo.toml
  atoma-proxy/Cargo.toml
  atoma-proxy/src/main.rs
  atoma-proxy/src/telemetry.rs
  loki.yaml
Labels: deployment, observability

#292 build: add bootstrap proxy config
  Cargo.lock
  config.example.toml
  deny.toml
  docker-compose.yaml
Labels: atoma-p2p

#293 build: add local_key to .gitignore
  .gitignore
Labels: atoma-p2p

#294 chore: add retries to openapi
  atoma-proxy-service/src/components/openapi.rs
Labels: enhancement

#296 chore: add metrics for ITL and TTFT
  atoma-proxy/src/server/handlers/metrics.rs
  atoma-proxy/src/server/streamer.rs
Labels: metrics

#309 feat: update logs nvidia evidence attestation
  atoma-state/src/handlers.rs
Labels: confidential-compute

#313 chore: configurable logs for docker containers
  docker-compose.yaml
Labels: deployment, observability

#318 chore: use env variable to set logging levels
  .env.example
  Dockerfile
  README.md
  docker-compose.dev.yaml
  docker-compose.yaml
Labels: deployment, observability

#329 ci: ignore sui SDK related audits for now
  .github/workflows/audit.yml
Labels: documentation, sui

#328 build: add taplo formatting
  .github/workflows/ci.yml
  .vscode/settings.json
  Cargo.toml
  atoma-auth/Cargo.toml
  atoma-proxy-service/Cargo.toml
  atoma-proxy/Cargo.toml
  atoma-state/Cargo.toml
  config.example.toml
  deny.toml
  rustfmt.toml
  taplo.toml
Labels: documentation, dependencies

#343 feat: handle potential locked stacks
  Cargo.lock
  atoma-state/src/migrations/20250327153220_lock-almost-full-stacks.sql
  atoma-state/src/state_manager.rs
Labels: state

#348 feat: handle locked status code openrouter
  Cargo.lock
  atoma-proxy/src/server/http_server.rs
  atoma-proxy/src/server/middleware.rs
  atoma-state/src/handlers.rs
  atoma-state/src/migrations/20250327153220_lock-almost-full-stacks.sql
  atoma-state/src/state_manager.rs
  atoma-state/src/types.rs
Labels: state

#350 feat: handle streamer drop openrouter
  atoma-proxy/src/server/handlers/chat_completions.rs
  atoma-proxy/src/server/handlers/embeddings.rs
  atoma-proxy/src/server/handlers/image_generations.rs
  atoma-proxy/src/server/handlers/metrics.rs
  atoma-proxy/src/server/handlers/request_model.rs
  atoma-proxy/src/server/middleware.rs
  atoma-proxy/src/server/streamer.rs
Labels: openai-api
