Repository atoma-network/atoma-proxy, pull requests merged in 2025-02, with the labels that each got.

#194 build: update openssl dep
  Cargo.lock
Labels: dependencies

#201 feat: telemetry
  .env.example
  Cargo.lock
  atoma-proxy/Cargo.toml
  atoma-proxy/src/main.rs
  atoma-proxy/src/server/handlers/chat_completions.rs
  atoma-proxy/src/server/handlers/embeddings.rs
  atoma-proxy/src/server/handlers/image_generations.rs
  atoma-proxy/src/server/handlers/metrics.rs
  atoma-proxy/src/server/handlers/mod.rs
  atoma-proxy/src/server/http_server.rs
  atoma-proxy/src/telemetry.rs
  docker-compose.yaml
Labels: metrics

#205 build: updated observability configs
  docker-compose.yaml
  loki.yaml
  otel-collector-config.yaml
  prometheus.yml
  tempo.yaml
Labels: metrics

#206 build: update grafana config
  .env.example
  docker-compose.yaml
Labels: metrics

#64 feat: verification and public url storing through atoma p2p network of peers
  Cargo.lock
  Cargo.toml
  atoma-auth/src/sui/mod.rs
  atoma-proxy/Cargo.toml
  atoma-proxy/src/main.rs
  atoma-state/Cargo.toml
  atoma-state/src/handlers.rs
  atoma-state/src/migrations/20250205174956_add-timestamp-to-nodes-table.sql
  atoma-state/src/state_manager.rs
Labels: enhancement, deployment, atoma-p2p

#216 fix: add further configs to scrape jobs for tempo and loki
  atoma-proxy/src/telemetry.rs
  docker-compose.yaml
  otel-collector-config.yaml
Labels: observability

#219 feat: update openai api to handle contents in array form
  atoma-proxy/Cargo.toml
  atoma-proxy/docs/openapi.yml
  atoma-proxy/src/server/handlers/chat_completions.rs
  atoma-proxy/src/server/handlers/embeddings.rs
  atoma-proxy/src/server/handlers/image_generations.rs
  atoma-proxy/src/server/handlers/request_model.rs
  atoma-proxy/src/server/middleware.rs
Labels: enhancement, openai-api

#224 feat: add client message to internal error
  atoma-proxy/src/server/error.rs
  atoma-proxy/src/server/handlers/chat_completions.rs
  atoma-proxy/src/server/handlers/embeddings.rs
  atoma-proxy/src/server/handlers/image_generations.rs
  atoma-proxy/src/server/handlers/mod.rs
  atoma-proxy/src/server/handlers/nodes.rs
  atoma-proxy/src/server/middleware.rs
  atoma-proxy/src/server/mod.rs
Labels: enhancement, openai-api

#226 feat: add v1/models auth
  atoma-proxy/docs/openapi.yml
  atoma-proxy/src/server/handlers/chat_completions.rs
  atoma-proxy/src/server/handlers/embeddings.rs
  atoma-proxy/src/server/handlers/models.rs
Labels: openai-api

#228 feat: add usage examples for responses
  atoma-proxy/docs/openapi.yml
  atoma-proxy/src/server/handlers/chat_completions.rs
Labels: openai-api

#230 feat: add more examples for openapi schema
  atoma-proxy/docs/openapi.yml
  atoma-proxy/src/server/handlers/chat_completions.rs
Labels: openai-api

#222 feat: node scores computation and storage
  Cargo.lock
  Cargo.toml
  atoma-state/Cargo.toml
  atoma-state/src/config.rs
  atoma-state/src/handlers.rs
  atoma-state/src/migrations/20241213104339_create_initial_schema.sql
  atoma-state/src/migrations/20241219152013_key_rotations.sql
  atoma-state/src/migrations/20241230131705_add_balance_table.sql
  atoma-state/src/migrations/20250108092319_add-usdc-digest-table.sql
  atoma-state/src/migrations/20250210104118_node-metrics.sql
  atoma-state/src/migrations/20250211181607_add-performance-metrics-table.sql
  atoma-state/src/state_manager.rs
  atoma-state/src/types.rs
  config.example.toml
Labels: enhancement, metrics, state, atoma-p2p

#234 docs: update `config.example.toml` with missing params
  config.example.toml
  docker-compose.yaml
Labels: documentation

#236 feat: explicity expose p2p service port
  .env.example
  config.example.toml
  docker-compose.yaml
Labels: deployment, atoma-p2p

#231 feat: add grafana dashboards
  Cargo.lock
  atoma-proxy-service/Cargo.toml
  atoma-proxy-service/docs/openapi.yml
  atoma-proxy-service/src/components/grafana.rs
  atoma-proxy-service/src/components/mod.rs
  atoma-proxy-service/src/components/openapi.rs
  atoma-proxy-service/src/config.rs
  atoma-proxy-service/src/handlers/stats.rs
  atoma-proxy-service/src/lib.rs
  atoma-proxy-service/src/proxy_service.rs
  atoma-proxy/src/main.rs
  config.example.toml
Labels: metrics

#242 ci: add docker-compose dev config
  docker-compose.dev.yaml
Labels: deployment

#243 build: remove unnecessary docker volumes
  docker-compose.dev.yaml
Labels: deployment

#249 build: update `Dockerfile` to use ubuntu for builds
  Dockerfile
Labels: deployment

#248 build: add port for postgres mapping for Github CI
  .env.example
  docker-compose.dev.yaml
Labels: deployment

#251 fix: update telemetry default endpoint
  atoma-proxy/src/telemetry.rs
Labels: metrics, observability

#260 build: add correct libp2p`loki` config
  atoma-proxy/src/telemetry.rs
  otel-collector-config.yaml
  prometheus.yml
Labels: metrics, atoma-p2p

#252 feat: add gpu vllm metrics to the proxy
  Cargo.lock
  Cargo.toml
  atoma-proxy/src/main.rs
  atoma-state/Cargo.toml
  atoma-state/src/config.rs
  atoma-state/src/errors.rs
  atoma-state/src/handlers.rs
  atoma-state/src/lib.rs
  atoma-state/src/metrics.rs
  atoma-state/src/migrations/20250223231316_remove-node-metrics-postgres.sql
  atoma-state/src/state_manager.rs
  atoma-state/src/tests.rs
  atoma-state/src/types.rs
Labels: metrics, state
